#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""GENERATED by plugins/alemax/build.py — do not edit.

Source: plugins/alemax/src/alemax/verbs/broadcast.py
Runs `alemax broadcast` from the vendored package beside this plugin. Stdlib only; a
project clone installs nothing.
"""

import sys
from pathlib import Path

# Resolved from THIS FILE, never from the working directory: a delivery is first
# executed inside a staged worktree at an arbitrary path.
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "_alemax"))

from alemax.cli import main

if __name__ == "__main__":
    sys.exit(main(["broadcast", *sys.argv[1:]]))
