N: 6
alt_model: model8
batch_size: 64
block_size: 256
d_ff: 1536
d_model: 384
datasource: tinyshakespeare
dropout: 0.2
experiment_name: runs/tmodel
h: 6
lang_src: en
lang_tgt: en
lr: 0.001
model_basename: tmodel_
num_epochs: 1
preload: latest
seq_len: 80
tokenizer_file: tokenizer_{0}
